version: '3'
services:
  app:
    container_name: line-poll-pub
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
